version: '3.7'

services:
  nasqarUiApp:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src/out:/usr/share/nginx/html:rw
      - type: bind
        source: "./conf/ssl.conf"
        target: "/etc/nginx/conf.d/default.conf"
        volume:
          nocopy: true
