version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
      - app3

  app1:
    build: 
      context: ./app1
    ports:
      - "3001:3232"

  app2:
    build: 
      context: ./app2
    ports:
      - "3002:3232"

  app3:
    build: 
      context: ./app3
    ports:
      - "3003:3232"

