channels:
- bioconda
- conda-forge
- defaults
dependencies:
- r-base==4.3.3
- r-DT
- r-Matrix
- r-NMF
- r-RColorBrewer
- r-SeuratObject
- r-base==4.3.3
- r-biocmanager
- r-car
- r-clustree
- r-devtools
- r-dplyr
- r-dt
- r-europepmc
- r-future
- r-ggplot2
- r-ggpubr
- r-ggrastr
- r-ggrepel
- r-ggridges
- r-ggthemes
- r-ggupset
- r-ggvis
- r-gplots
- r-heatmaply
- r-httr
- r-lme4
- r-magrittr
- r-markdown
- r-nloptr
- r-pheatmap
- r-plotly
- r-rclipboard
- r-readr
- r-reshape2
- r-reticulate
- r-rhandsontable
- r-rspectra
- r-rstatix
- r-sf
- r-shiny
- r-shinyBS
- r-shinycssloaders
- r-shinydashboard
- r-shinyjs
- r-sodium
- r-spdep
- r-stringr
- r-terra
- r-tidyr
- r-uuid
- r-uwot
- r-v8
- r-vegan
- r-vennDiagram
- bioconductor-animalcules
- bioconductor-atacseqqc
- bioconductor-batchelor
- bioconductor-biocgenerics
- bioconductor-chippeakanno
- bioconductor-clusterprofiler
- bioconductor-complexheatmap
- bioconductor-dada2
- bioconductor-debrowser
- bioconductor-delayedarray
- bioconductor-delayedmatrixstats
- bioconductor-deseq2
- bioconductor-edger
- bioconductor-enhancedvolcano
- bioconductor-genomicalignments
- bioconductor-glmgampoi
- bioconductor-hdf5array
- bioconductor-interactivecomplexheatmap
- bioconductor-limma
- bioconductor-limmagui
- bioconductor-motifdb
- bioconductor-multiassayexperiment
- bioconductor-pathview
- bioconductor-phyloseq
- bioconductor-rsamtools
- bioconductor-s4vectors
- bioconductor-singlecellexperiment
- bioconductor-summarizedexperiment
- bioconductor-sva
- biom-format
- bpp-core
- gcc_linux-64
- gxx_linux-64
- presto
- r-seurat #added for BPcells monocle deps
- binutils #added for BPcells monocle deps
name: merged_env
