name: v_dada2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base==4.3.3
  - r-dplyr
  - r-shiny
  - r-shinydashboard
  - r-shinyjs
  - r-shinyBS
  - r-shinycssloaders
  - r-DT
  - r-markdown
  - r-tidyr
  - r-httr
  - bioconductor-dada2
  - bioconductor-phyloseq
