tabItem(
    tabName = "trackReadsTab",
    
    # Descriptions for the Track Reads Summary, Download Processed Files, and Plots
    fluidRow(
        column(
            12,
            box(
                title = "Overview", solidHeader = TRUE, status = "info", width = 12, collapsible = TRUE, collapsed = FALSE,
                HTML("
                <p>This page provides multiple features to analyze and download results from the DADA2 pipeline:</p>
                <ul>
                    <li><b>Track Reads Summary:</b> This table shows how many reads passed through each step of the DADA2 pipeline, allowing you to check for any significant drops at each step. This helps you verify that your data is being processed correctly.</li>
                    <li><b>Download Processed Files:</b> You can download the processed files generated by DADA2 at different stages. This includes denoised forward and reverse reads, and non-chimeric sequences. These are available as ZIP files for easy access.</li>
                   
                </ul>
                ")
                #  <li><b>Sequence Abundance Plot:</b> You can either select a sequence from a dropdown menu or paste a sequence to plot its abundance across samples, providing insights into the distribution of specific sequences in your data.</li>
            )
        )
    ),
    
    # Track Reads Summary Box
    fluidRow(
        column(
            12,
            box(
                title = "Track Reads Summary", solidHeader = TRUE, status = "primary", width = 12, collapsible = TRUE, collapsed = FALSE,
                withSpinner(dataTableOutput("trackTable")),
                downloadButton("download_track_table", "Download Track Reads Table", class = "btn-primary", style = "margin-top: 10px;")
            )
        )
    ),
    
    # Download Processed Files Box
    fluidRow(
        column(
            12,
            box(
                title = "Download Processed Files",
                solidHeader = TRUE,
                status = "primary",
                width = 12,
                collapsible = TRUE,
                collapsed = FALSE,
                wellPanel(
                    fluidRow(
                        column(
                            3,
                            div(
                                style = "text-align: center;",
                                downloadButton("download_zip_denoisedF",
                                    "Download Denoised Forward Read as ZIP",
                                    class = "btn-block"
                                )
                            )
                        ),
                        column(
                            3,
                            div(
                                style = "text-align: center;",
                                downloadButton("download_zip_denoisedR",
                                    "Download Denoised Reverse Read as ZIP",
                                    class = "btn-block"
                                )
                            )
                        ),
                        column(
                            3,
                            div(
                                style = "text-align: center;",
                                downloadButton("download_zip_nonchim",
                                    "Download Non-chimeric (per sample) as ZIP",
                                    class = "btn-block"
                                )
                            )
                        ),
                        column(
                            3,
                            div(
                                style = "text-align: center;",
                                downloadButton("download_nonchim",
                                    "Download Non-chimeric Fasta",
                                    class = "btn-block"
                                )
                            )
                        )
                    )
                )
            )
        )
    ),
    
    # # Select or Paste Sequence for Abundance Plot Box
    # fluidRow(
    #     column(
    #         12,
    #         box(
    #             title = "Select or Paste Sequence for Abundance Plot",
    #             solidHeader = TRUE,
    #             status = "primary",
    #             width = 12,
    #             collapsible = TRUE,
    #             collapsed = FALSE,
    #             fluidRow(
    #                 column(
    #                     6,
    #                     div(
    #                         selectInput("sequence_select", "Select Sequence:",
    #                             choices = NULL, # This will be populated dynamically
    #                             multiple = FALSE,
    #                             selectize = TRUE, # Enable search functionality
    #                             width = "100%" # Ensure it adjusts to full width
    #                         )
    #                     )
    #                 ),
    #                 column(
    #                     6,
    #                     textAreaInput("sequence_input", "Paste Sequence:", rows = 5, placeholder = "Paste a sequence here...")
    #                 )
    #             ),
    #             actionButton("plot_sequence_abundance", "Plot Abundance", class = "btn-primary", style = "margin-top: 10px;")
    #         )
    #     )
    # ),
    
    # # Abundance Plot Box
    # fluidRow(
    #     column(
    #         12,
    #         box(
    #             title = "Abundance of Selected Sequence",
    #             solidHeader = TRUE,
    #             status = "primary",
    #             width = 12,
    #             collapsible = TRUE,
    #             collapsed = FALSE,
    #             withSpinner(plotOutput("sequenceAbundanceBarChart"))
    #         )
    #     )
    # )
)
