name: v_debrowser
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base==4.3.3
  - r-shiny
  - r-shinydashboard
  - r-shinyjs
  - r-shinyBS
  - r-shinycssloaders
  - bioconductor-debrowser
