name: v_enrichORA
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base==4.3.3
  - r-shiny
  - r-shinydashboard
  - r-shinyjs
  - r-shinyBS
  - r-shinycssloaders
  - r-devtools
  - r-sodium
  - r-DT
  - r-markdown
  - r-biocmanager
  - r-ggupset
  - bioconductor-clusterprofiler
  - bioconductor-pathview
